### PR TITLE
added support for repeating instruments

### PR DESCRIPTION
**Pull request by mschulze0**

### CODE REVIEW

**Comment by mschulze0** [comment]
I didn't check if this works with repeating events.

**Comment by mschulze0** [comment]
@scottjpearson It works fine with non-repeating forms as well. Why would I pay you for this? That makes no sense. I'm providing you the code, so if anything you should be paying me. In the end it's your loss if you keep an undocumented error in your module (as it's not mentioned anywhere in the documentation that the module doesn't work with repeating forms).

**Comment by carlreedw** [comment]
Hello mschulze0. Thank you for your PR. I'm seeing this late but am commenting to say support for repeating instances was added to the module with commit 9463de0 on January 11th, 2021.

**Comment by mmcev106** [comment]
@mschulze0, I just wanted to say thank for this PR, and I'm very sorry you didn't get some kind of response much sooner.  I'm going to "watch" this repo & respond to new issues & PRs going forward.  Additional PRs would be welcome, and should get at least a basic response within a few days!

**Comment by mmcev106** [comment]
@mschulze0, version 1.3.0 of this module was just released to the repo including @carlreedw's repeating instance fix.

**Comment by mschulze0** [comment]
> @mschulze0, version 1.3.0 of this module was just released to the repo including @carlreedw's repeating instance fix.

Just tested it and unfortunately it doesn't work for me. It's still piping the data for the most recent instance of the repeating instrument instead of the current instance. Just to be clear I have a repeating instrument in the DESTINATION project that contains the ID.

**Comment by mmcev106** [comment]
@mschulze0, we're trying to get a few hours approved to look into this.  A new PR would be welcome if you're interested.

**Comment by mschulze0** [comment]
> @mschulze0, we're trying to get a few hours approved to look into this. A new PR would be welcome if you're interested.

My original PR still works. The main part is this in getValue.php:

` foreach ($thisdata as $instance => $line) {
                if ($instance == $instance_i-1 && $line[$thismatch]) {
                        $matchRecord = $line[$thismatch];
                }
        }`

**Comment by carlreedw** [comment]
@mschulze0 

I tested out your PR but couldn't get it to pipe field data into my record when I pressed "Initiate Data Piping" button on the data entry page.

I think this is because the line you highlighted:

`foreach ($thisdata as $instance => $line) { if ($instance == $instance_i-1 && $line[$thismatch]) { $matchRecord = $line[$thismatch]; } }`

$instance_i is never defined. In your actual PR you have that correctly listed as $thisinstance but I think you also expect '$thisdata' to be an array with more than 1 element. In my testing, that wasn't the case. My `$thisdata` only has 1 element, an array that contains the record_id value:

`$thisdata in getValue: Array
(
    [0] => Array
        (
            [record_id] => 1
            [redcap_repeat_instrument] => 
            [redcap_repeat_instance] => 
        )

)`

So when `$thisinstance` is greater than 1, `$matchRecord` is null, causing `getValue.php` to exit on line 29:
`	if(empty($matchRecord)){
		// Return without echo-ing any values.
		return;
	} else`

Maybe another thing preventing getValue from returning the correct repeat instance field value is that the 'repeat_instances' element of $recData is never accessed in lines 88-124. Is LogicTester::apply supposed to return the repeat instance value as $result?

**Comment by mschulze0** [comment]
@carlreedw $instance_i is a new variable from 0da9a9888b5399557f209013a504c6dfa7997e27 which i adapted the above code to.
my $thisdata has more than one element because it contains data that's on a repeating form. I guess there needs to be a check whether you're dealing with repeating forms or not.

**Comment by mmcev106** [comment]
@carlreedw, I don't work with all the different possible REDCap project types often enough to be confident on exactly what is needed here without doing some research & testing.  However, I just wrote [this code block](https://github.com/vanderbilt-redcap/fhir-services-module/blob/025d48015e97b001b278d84948dd94620d3bc8e5/FHIRServicesExternalModule.php#L2521-L2529) based on the `Survey::getEconsentOptionsData()` method which Rob wrote in REDCap core.  Does it cover all scenarios?

**Comment by carlreedw** [comment]
@mmcev106 In my testing, I've only seen the case where '$thisdata' has one element, regardless of whether or not the instrument being piped to/from is repeating or not.

**Comment by carlreedw** [comment]
@mschulze0
I believe we may have been talking past each other, as I think v1.2.2 of the module did not support longitudinal projects (projects with defined events). And I suspect maybe your PR is target repeating events instead of repeating instruments.

There's a difference in how the data is stored/formatted for repeating instruments vs repeating events (and consequently repeating instruments in repeating events). Did your test project indeed have repeating events?

**Comment by mschulze0** [comment]
> @mschulze0
> I believe we may have been talking past each other, as I think v1.2.2 of the module did not support longitudinal projects (projects with defined events). And I suspect maybe your PR is target repeating events instead of repeating instruments.
> 
> There's a difference in how the data is stored/formatted for repeating instruments vs repeating events (and consequently repeating instruments in repeating events). Did your test project indeed have repeating events?

No, it's for repeating instruments where the ID and piped fields are on that repeating instrument (in the destination project) and it's working fine for me.
The structure for the destination project is:
- classic project (not longutidunal)
- Form 1, repeating. This is where the ID and piped fields are.
- Form 2, not repeating. completely unrelated to cross-project-piping

 (Repeating instruments within repeating events are currently not possibe in REDCap.)

**Comment by carlreedw** [comment]
Ah. You are correct about REDCap not allowing repeating instruments on repeating events.

I think I'm starting to see why we're diverging. You've configured the "Unique Match Field" value to be a field that is on a repeating instrument, aren't you?

I think that is what will yield a multi-element '$thisdata'. Meanwhile my configuration uses a "Unique Match Field" that is on a non-repeating form -- resulting always in just one element.

I tested your PR some more and can pull data from source projects now, but the pulled data value is always from the source form's first instance, for me.

**Comment by mschulze0** [comment]
> Ah. You are correct about REDCap not allowing repeating instruments on repeating events.
> 
> I think I'm starting to see why we're diverging. You've configured the "Unique Match Field" value to be a field that is on a repeating instrument, aren't you?
> 
> I think that is what will yield a multi-element '$thisdata'. Meanwhile my configuration uses a "Unique Match Field" that is on a non-repeating form -- resulting always in just one element.
> 
> I tested your PR some more and can pull data from source projects now, but the pulled data value is always from the source form's first instance, for me.

yes. unique match field is what I meant with ID.

So you also have repeating instruments in the source project? my PR doesn't address that case, so it's likely that the module needs to be adapted also for that case.

**Comment by carlreedw** [comment]
"So you also have repeating instruments in the source project?"

Yes.

**Pull request closed without merging**
